;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beginning-of-visual-line
	end-of-visual-line
	indent-for-tab-command
	org-beginning-of-line
	org-self-insert-command
	undefined
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-buffer
	))
